In [2]:
# numpy (2)
# 1. numpy 행렬 곱 (dot product) (1)
# : np.dot(A,B) => 행렬 A의 열 벡터와 B 행렬의 행 벡터가 같아야함.
# : 두 값이 다르다면 reshape() 혹은 transpose() 등을 사용해 형 변환을 해준 후 행렬 곱 실행해야함
import numpy as np

A = np.array([[1,2,3],[4,5,6]]) # 2x3행렬
B = np.array([[-1,-2],[-3,-4],[-5,-6]]) # 3x2행렬

# (2x3) dot product (3x2) == (2x2) 행렬
C = np.dot(A,B) # 행렬 곱 수행

# matrix A, B 형상 출력
print("A.shape ==", A.shape,"B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


In [4]:
# : 행렬곱은 1) 행렬곱 조건을 만족하는 다양한 크기의 행렬을 연속적으로 만들고
# 2) 행렬 곱을 연속적으로 계산하며, 3) 결과값을 만들 수 있기 때문에 
# 머신러닝과 이미지 프로세싱 분야에서 자주 사용됨

# 2. numpy broadcast
# : numpy에서는 크기가 다른 두 행렬간에도 사칙연산이 가능함 (dot product는 안됨)
# : 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후 계산

D = np.array([[1,2],[3,4]])
b = 5  # b를 2x2 가 모두 5로 채워진 행렬로 바꿔줌

print(D+b)

[[6 7]
 [8 9]]


In [5]:
E= np.array([4,5])
print (D+E) # E를 [[4,5],[4,5]] 로 변형시켜서 연산 실행

[[5 7]
 [7 9]]


In [6]:
# 3. numpy transpose 
# B=A.T 형식으로 표현
# vector는 transpose 안됨

F=A.T
print(F)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
# 4. numpy 행렬 indexing / slicing
# : list와 마찬가지로 인덱싱 슬라이싱 모두 가능
print("A[0,0] == ", A[0, 0])
print("A[:,:] ==", A[:,:])

A[0,0] ==  1
A[:,:] == [[1 2 3]
 [4 5 6]]


In [3]:
# 5. numpy 행렬 iterator
# : 행렬의 모든 원소를 access하는 경우 iterator 사용

import numpy as np

A = np.array([[10,20,30,40],[50,60,70,80]])

print(A, "\n")
print("A,shape ==", A.shape, "\n")

# 행렬 A 의 iterator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite']) 

# flags=['multi_index'] 라고 하면 iterator 생성후 반복할때 행렬처럼 (row, column) 형태의 multi_index 형태로 동작하라는 의미입니다.
# 그리고 op_flags 의미는 말 그대로 iterator 를 R/W 형태로 생성시킨다는 의미입니다.
# R/W 말고 RO 형태로 생성해도 문제없습니다

while not it.finished:
    
    idx = it.multi_index
    
    print("current value => ", A[idx]) 
    
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A,shape == (2, 4) 

current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
