In [6]:
# 답은 data shuffle 이었다.
# MNIST의 데이터가 순서대로 들어가다보니, 머신러닝 프로그램은
# 데이터를 순서대로 읽어들여 1이랑 2랑 일부 숫자만 학습한것이었다.
# Shufffle을 하니 바로 해결되었다 너무 뿌듯하다

# http://www.birc.co.kr/2018/02/26/%EC%8B%A4%EC%A0%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-cnn-%EB%AA%A8%EB%8D%B8-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0/
# 위 링크에서 보고 베낌 ㅎ_ㅎ

#train 파일 처리

import os
import cv2
# 이미지 파일을 불러올 때 사용하는 모듈

# cv2(opneCV)모듈 설치방법
# 개 뻘짓 3시간동안 했다..
# 본인이 사용하는 가상환경을 activation 한 후 설치하면 된다. 두줄이면 끝난다. 내가 3시간 동안 한것.^^ visual studio 설치 이런건 1도 필요없다
# conda activate virenv(내 가상환경 이름)
# conda install -c conda-forge opencv (최신 버전 설치해줌. 하위버전 python 3.7이랑 호환 안됨)
# jupyter notebook 도 가상환경 내에서 실행해야 된다.

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from numpy import array
 
TRAIN_DIR = 'C:/Users/olor095/LAY/Practice/CNN/trainingSet'
train_folder_list = array(os.listdir(TRAIN_DIR)) #training set 내부의 폴더를 리스트 형태로 받음

print("train_folder_list is\n", train_folder_list)
 
train_input = [] 
train_label = [] # 빈 리스트 할당
 
label_encoder = LabelEncoder()  # LabelEncoder Class 호출
integer_encoded = label_encoder.fit_transform(train_folder_list)
#문자열로 구성된 train_folder_list를 숫자로 바꿔줌

print("integer_encoded is\n", integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False) 

integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
#onehotencoder 사용을 위해, (10,)의 list형태에서 (10,1)의 행렬로 변환시켜줌

onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
#integer_encoded를 10x10 행렬로 바꿔줌

print("onehot_encoded is\n", onehot_encoded)
    
for index in range(len(train_folder_list)): #변수 0-9까지 for 구문 반복
    path = os.path.join(TRAIN_DIR, train_folder_list[index])
    #train_folder_list의 n번째 원소를 합쳐서 path에 저장
    print("index is",index)
    print("path is", path)
    path = path + '/'
    # path 변수에 / 추가
    # print 하면 path 맨 마지막에 / 추가됨
    img_list = os.listdir(path)
    for img in img_list:
        img_path = os.path.join(path, img)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        #이 부분에서 이미지를 흑백으로 불러온다. 준규 말대로 여기서 minmaxscaling을 해줘서 데이터 전처리를 해주려고 한다.
        scaler = MinMaxScaler()
        scaler.fit(img)
        img=scaler.transform(img)
#        print(img) 하면 데이터가 변환되었음을 볼수 있다 하지만 이걸 실행하면 컴퓨터가 아파하므로 잠시 실행해보고 끄도록 하자
#        Scaling을 해주기 이전에 데이터들은 훨씬 더 큰 값을 가졌다는걸 그 전에 프린트 구문을 실행해보면 알 수 있다. 
        train_input.append([np.array(img)])
        train_label.append([np.array(onehot_encoded[index])])
 
train_input = np.reshape(train_input, (-1, 784))
train_label = np.reshape(train_label, (-1, 10))
train_input = np.array(train_input).astype(np.float32)
train_label = np.array(train_label).astype(np.float32)
np.save("train_data.npy", train_input)
np.save("train_label.npy", train_label)

train_folder_list is
 ['0_zero' '1_one' '2_two' '3_three' '4_four' '5_five' '6_six' '7_seven'
 '8_eight' '9_nine']
integer_encoded is
 [0 1 2 3 4 5 6 7 8 9]
onehot_encoded is
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
index is 0
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\0_zero
index is 1
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\1_one
index is 2
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\2_two
index is 3
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\3_three
index is 4
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\4_four
index is 5
path is C:/Users/olor095/LAY/Practice/CNN/trainingSet\5_five
index is 6
path is C:/Users/olor095/LAY/Practice/CNN/trainingS

In [7]:
#test 파일 처리

TEST_DIR = 'C:/Users/olor095/LAY/Practice/CNN/testSet/'
test_folder_list = array(os.listdir(TEST_DIR))
 
test_input = []
test_label = []
 
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(test_folder_list)
onehot_encoder = OneHotEncoder(sparse=False) 
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
 
for index in range(len(test_folder_list)):
    path = os.path.join(TEST_DIR, test_folder_list[index])
    path = path + '/'
    img_list = os.listdir(path)
    for img in img_list:
        img_path = os.path.join(path, img)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        scaler = MinMaxScaler()
        scaler.fit(img)
        img=scaler.transform(img)
        test_input.append([np.array(img)])
        test_label.append([np.array(onehot_encoded[index])])
 
test_input = np.reshape(test_input, (-1, 784))
test_label = np.reshape(test_label, (-1, 10))
test_input = np.array(test_input).astype(np.float32)
test_label = np.array(test_label).astype(np.float32)
np.save("test_input.npy",test_input)
np.save("test_label.npy",test_label)

In [8]:
#CNN 모델 구성



#import tensorflow as tf
#import tensorflow_addons as tfa
#import keras as keras
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()  
import tensorflow as tf2

tf.reset_default_graph()
# 여러번 돌리면 가중치(W3)이 이미 존재해서 안돌아갈때가 있다. 그럴땐 이 코드를 삽입해서 실행해주면 문제없이 실행된다. 
# 그리고 #을 넣어서 없애버리자. 
# 참고 링크
# https://calcifer1009-dev.tistory.com/10


# hyper parameters
learning_rate = 0.001
    
# Convolution layer를 만드는 부분
# 일반적인 MNIST CNN 과정이랑 똑같다

X = tf.placeholder(tf.float32, [None, 784])
X_img = tf.reshape(X, [-1, 28, 28, 1])   # img 28x28x1 (black/white)
Y = tf.placeholder(tf.float32, [None, 10])
 
W1 = tf.Variable(tf.random_normal([3, 3, 1, 32], stddev=0.01))
L1 = tf.nn.conv2d(X_img, W1, strides=[1, 1, 1, 1], padding='SAME')
L1 = tf.nn.relu(L1)
L1 = tf.nn.max_pool(L1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')
 
W2 = tf.Variable(tf.random_normal([3, 3, 32, 64], stddev=0.01))
L2 = tf.nn.conv2d(L1, W2, strides=[1, 1, 1, 1], padding='SAME')
L2 = tf.nn.relu(L2)
L2 = tf.nn.max_pool(L2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

W3 = tf.Variable(tf.random_normal([3, 3, 64, 128], stddev=0.01))
L3 = tf.nn.conv2d(L2, W3, strides=[1, 1, 1, 1], padding='SAME')
L3 = tf.nn.relu(L3)
L3 = tf.nn.max_pool(L3, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

W4 = tf.Variable(tf.random_normal([3, 3, 128, 256], stddev=0.01))
L4 = tf.nn.conv2d(L2, W3, strides=[1, 1, 1, 1], padding='SAME')
L4 = tf.nn.relu(L4)
L4 = tf.nn.max_pool(L2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

print(L4)

L5_flat = tf.reshape(L4, [-1, 4 * 4 * 64])
sigma = 1
W5 = tf.get_variable("W5", shape=[4 * 4 * 64, 10], initializer=tf.variance_scaling_initializer(mode="fan_avg", distribution="uniform", scale=sigma))
# xavier를 이전 initializer로 바꾸어 주었다. 


b = tf2.Variable(tf.random_normal([10]))
logits = tf.matmul(L5_flat, W5) + b

# 은닉층을 5층으로 늘림, 안에 들어가는 값 계산하는거 살짝 귀찮다. 
 
# define cost/loss &amp;amp;amp; optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(
    logits=logits, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)


Tensor("MaxPool_3:0", shape=(?, 4, 4, 64), dtype=float32)


In [9]:
#모델 학습
training_epochs = 15
batch_size = 100
 
# initialize
sess = tf.Session()
sess.run(tf.global_variables_initializer())
 
# train my model
print('Learning started. It takes sometime.')
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(len(train_input) / batch_size)
    shuffle_indices = np.random.permutation(np.arange(len(train_label))) 
    train_input = train_input[shuffle_indices]
    train_label = train_label[shuffle_indices]
    for i in range(total_batch):
        start = ((i+1) * batch_size) - batch_size
        end = ((i+1) * batch_size)
        batch_xs = train_input[start:end]
        batch_ys = train_label[start:end]
        feed_dict = {X: batch_xs, Y: batch_ys}
        c, _ = sess.run([cost, optimizer], feed_dict=feed_dict)
        # 별로 안중요한걸 저장할땐 _ 이거 쓰는게 약간 국룰인가보다
        avg_cost += c / total_batch
 
    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))
 
print('Learning Finished!')

Learning started. It takes sometime.
Epoch: 0001 cost = 0.655575616
Epoch: 0002 cost = 0.170067480
Epoch: 0003 cost = 0.128133513
Epoch: 0004 cost = 0.111301122
Epoch: 0005 cost = 0.096119225
Epoch: 0006 cost = 0.081803703
Epoch: 0007 cost = 0.075220855
Epoch: 0008 cost = 0.067972939
Epoch: 0009 cost = 0.061891255
Epoch: 0010 cost = 0.055200747
Epoch: 0011 cost = 0.051159663
Epoch: 0012 cost = 0.046771022
Epoch: 0013 cost = 0.043467228
Epoch: 0014 cost = 0.040517478
Epoch: 0015 cost = 0.036756488
Learning Finished!


In [10]:
#모델 정확도 산출
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: test_input, Y: test_label}))

Accuracy: 0.985
